### ISSUE TITLE
execve causes snapcraft-preload to crash

### ISSUE THREAD

**Issue by 3v1n0** [sergiusens/snapcraft-preload#11]
This is due to commit https://github.com/sergiusens/snapcraft-preload/commit/2bdb2873541bf3c6073b89011992cd8e1145ace5 and particularly [this hunk](https://github.com/sergiusens/snapcraft-preload/pull/6/files#diff-c311d118f6ff7ff1da8857ab800f20c6R637) as `strncat` doesn't properly find the string end of the previous copy (as that don't include the final `\0`).

Solution to this is both going back to use `strcpy` and `strcat` or using explicit addresses.

Ubuntu [review-tools snap](https://git.launchpad.net/review-tools/) is affected and I got these stack traces:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
*** Error in `/snap/review-tools/x1/usr/bin/python3': free(): invalid next size (fast): 0x0000000000ec4290 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffff78687e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7ffff7870e0a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ffff787498c]
/snap/review-tools/x1/lib/libsnapcraft-preload.so(+0x3cd3)[0x7ffff7ff2cd3]
/snap/review-tools/x1/lib/libsnapcraft-preload.so(execve+0x2f)[0x7ffff7ff2d62]
/snap/review-tools/x1/lib/libsnapcraft-preload.so(execv+0x2d)[0x7ffff7ff2d31]
/snap/review-tools/x1/usr/bin/python3[0x5eaa85]
/snap/review-tools/x1/usr/bin/python3(PyCFunction_Call+0x4f)[0x4e9b9f]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x614)[0x524414]
/snap/review-tools/x1/usr/bin/python3[0x52d82f]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x5532)[0x529332]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalCodeEx+0x13b)[0x52e12b]
/snap/review-tools/x1/usr/bin/python3[0x4ebdd7]
/snap/review-tools/x1/usr/bin/python3(PyObject_Call+0x47)[0x5b7167]
/snap/review-tools/x1/usr/bin/python3[0x4f413e]
/snap/review-tools/x1/usr/bin/python3(PyObject_Call+0x47)[0x5b7167]
/snap/review-tools/x1/usr/bin/python3[0x54d359]
/snap/review-tools/x1/usr/bin/python3[0x55d17c]
/snap/review-tools/x1/usr/bin/python3(PyObject_Call+0x47)[0x5b7167]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x4f06)[0x528d06]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x4a14)[0x528814]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x4a14)[0x528814]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x4a14)[0x528814]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x4a14)[0x528814]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x4a14)[0x528814]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalFrameEx+0x4a14)[0x528814]
/snap/review-tools/x1/usr/bin/python3[0x52d2e3]
/snap/review-tools/x1/usr/bin/python3(PyEval_EvalCode+0x1f)[0x52dfdf]
/snap/review-tools/x1/usr/bin/python3[0x5fd2c2]
/snap/review-tools/x1/usr/bin/python3(PyRun_FileExFlags+0x9a)[0x5ff76a]
/snap/review-tools/x1/usr/bin/python3(PyRun_SimpleFileExFlags+0x1bc)[0x5ff95c]
/snap/review-tools/x1/usr/bin/python3(Py_Main+0x456)[0x63e7d6]
/snap/review-tools/x1/usr/bin/python3(main+0xe1)[0x4cfe41]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ffff7811830]
/snap/review-tools/x1/usr/bin/python3(_start+0x29)[0x5d5f29


==10264== Conditional jump or move depends on uninitialised value(s)
==10264==    at 0x4C30C17: strcat (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10264==    by 0x402C811: ensure_in_ld_preload (preload.c:597)
==10264==    by 0x402C999: execve_copy_envp (preload.c:629)
==10264==    by 0x402CC28: execve_wrapper (preload.c:692)
==10264==    by 0x402CD61: execve (preload.c:734)
==10264==    by 0x5EA7F8: ??? (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x4E9B9E: PyCFunction_Call (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x524413: PyEval_EvalFrameEx (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x52D82E: ??? (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x529331: PyEval_EvalFrameEx (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x52E12A: PyEval_EvalCodeEx (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x4EBDD6: ??? (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264== 
==10264== Conditional jump or move depends on uninitialised value(s)
==10264==    at 0x4C30DD7: strncat (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10264==    by 0x402CA35: execve_copy_envp (preload.c:637)
==10264==    by 0x402CC28: execve_wrapper (preload.c:692)
==10264==    by 0x402CD61: execve (preload.c:734)
==10264==    by 0x5EA7F8: ??? (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x4E9B9E: PyCFunction_Call (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x524413: PyEval_EvalFrameEx (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x52D82E: ??? (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x529331: PyEval_EvalFrameEx (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x52E12A: PyEval_EvalCodeEx (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x4EBDD6: ??? (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
==10264==    by 0x5B7166: PyObject_Call (in /media/marco/M.2-SSD/review-tools/prime/usr/bin/python3.5)
```

**Comment by 3v1n0** [comment]
Merging happened, this is now fixed (@jdstrand)

**Comment by jdstrand** [comment]
Sorry I didn't get a chance to look at the PR sooner. I did play with it today and it no longer segfaults, but the behavior is different:
```
$ snap-review ./review-tools_0.46+git_amd64.snap 
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
./review-tools_0.46+git_amd64.snap: pass
```

There are denials in syslog:
```
Apr 27 13:02:36 localhost kernel: [187978.461321] audit: type=1400 audit(1493316156.003:139807): apparmor="DENIED" operation="open" profile="snap.review-tools.snap-review" name="/etc/magic" pid=5460 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

/snap/review-tools/current/etc/magic exists in the snap. @3v1n0 and I discussed this a bit on IRC and he will look into it.

**Comment by sergiusens** [comment]
On Thu, Apr 27, 2017 at 3:03 PM, jdstrand <notifications@github.com> wrote:

> Sorry I didn't get a chance to look at the PR sooner. I did play with it
> today and it no longer segfaults, but the behavior is different:
>
> $ snap-review ./review-tools_0.46+git_amd64.snap
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> /etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
> ./review-tools_0.46+git_amd64.snap: pass
>
> There are denials in syslog:
>
> Apr 27 13:02:36 localhost kernel: [187978.461321] audit: type=1400 audit(1493316156.003:139807): apparmor="DENIED" operation="open" profile="snap.review-tools.snap-review" name="/etc/magic" pid=5460 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
>
> /snap/review-tools/current/etc/magic exists in the snap. @3v1n0
> <https://github.com/3v1n0> and I discussed this a bit on IRC and he will
> look into it.
>
Interestingly, this is how I solved this problem for snapcraft this way:
https://github.com/snapcore/snapcraft/pull/1283/files

We are not using preload though.

**Comment by jdstrand** [comment]
@sergiusens - thanks for that. As it happens, the only reason I'm using preload is for python3-magic (well, that I know of-- if I undo the preload I might discover other things). Thanks for pointer. I'll check it out.

**Comment by sergiusens** [comment]
On Fri, Apr 28, 2017 at 3:21 PM, jdstrand <notifications@github.com> wrote:

> @sergiusens <https://github.com/sergiusens> - thanks for that. As it
> happens, the only reason I'm using preload is for python3-magic (well, that
> I know of-- if I undo the preload I might discover other things). Thanks
> for pointer. I'll check it out.
>
No worries, I had to read the file/magic source code to figure this one
out.
